export type markets = "crypto" |
                      "forex" |
                      "america" |
                      "uk" |
                      "india" |
                      "spain" |
                      "russia" |
                      "australia" |
                      "brazil" |
                      "japan" |
                      "newzealand" |
                      "turkey" |
                      "switzerland" |
                      "hongkong" |
                      "taiwan" |
                      "netherlands" |
                      "belgium" |
                      "portugal" |
                      "france" |
                      "mexico" |
                      "canada" |
                      "colombia" |
                      "uae" |
                      "nigeria" |
                      "singapore" |
                      "germany" |
                      "peru" |
                      "poland" |
                      "italy" |
                      "argentina" |
                      "israel" |
                      "egypt" |
                      "serbia" |
                      "chile" |
                      "china" |
                      "malaysia" |
                      "ksa" |
                      "bahrain" |
                      "qatar" |
                      "indonesia" |
                      "finland" |
                      "iceland" |
                      "denmark" |
                      "romania" |
                      "hungary" |
                      "sweden" |
                      "slovakia" |
                      "lithuania" |
                      "luxembourg" |
                      "estonia" |
                      "latvia" |
                      "vietnam" |
                      "rsa" |
                      "thailand" |
                      "korea" |
                      "norway" |
                      "philippines" |
                      "greece" |
                      "venezuela";
